In [5]:
import pandas as pd


# 读取当前目录下的sample.tsv 
df = pd.read_csv('sample.tsv', sep='\t')

# 取df的Sample ID列，Series ID列，Study Title列
df = df[['Sample ID', 'Series ID', 'Study Title']]
df

      Sample ID  Series ID                                        Study Title
0     GSM675519   GSE27323  Transcriptomic response to substrate and tempe...
1     GSM675520   GSE27323  Transcriptomic response to substrate and tempe...
2     GSM675521   GSE27323  Transcriptomic response to substrate and tempe...
3     GSM675522   GSE27323  Transcriptomic response to substrate and tempe...
4     GSM675523   GSE27323  Transcriptomic response to substrate and tempe...
..          ...        ...                                                ...
168  GSM5035235  GSE165516  Transcriptional profiling of Myceliophthora th...
169  GSM5035236  GSE165516  Transcriptional profiling of Myceliophthora th...
170  GSM5035237  GSE165516  Transcriptional profiling of Myceliophthora th...
171  GSM5035238  GSE165516  Transcriptional profiling of Myceliophthora th...
172  GSM5035239  GSE165516  Transcriptional profiling of Myceliophthora th...

[173 rows x 3 columns]

In [31]:
df2 = pd.read_csv('dataset.tsv', sep = '\t')
df2 = df2[['GEO Series', 'Publication']]

# 将GEO Series列名改为Series ID
df2.rename(columns={'GEO Series': 'Series ID'}, inplace=True)
df2

    Series ID  Publication
0    GSE27323   21964414.0
1   GSE183387          NaN
2   GSE184074   35257374.0
3   GSE205182   36165620.0
4   GSE214002   36691040.0
5   GSE214142   36478865.0
6   GSE110062   29843921.0
7   GSE111986   30474279.0
8   GSE114057   31078793.0
9    GSE57235   24881579.0
10  GSE137286   31534479.0
11  GSE165516   33995328.0

In [32]:
# 将Publication的值中的.0替换为空
df2['Publication'] = df2['Publication'].astype(str).str.replace('.0', '')
df2

    Series ID Publication
0    GSE27323    21964414
1   GSE183387         nan
2   GSE184074    35257374
3   GSE205182    36165620
4   GSE214002    36691040
5   GSE214142    36478865
6   GSE110062    29843921
7   GSE111986    30474279
8   GSE114057    31078793
9    GSE57235    24881579
10  GSE137286    31534479
11  GSE165516    33995328

In [38]:
# 将df和df2合并，根据Series ID列
df3 = pd.merge(df, df2, on='Series ID', how='left')
df3 = df3[['Sample ID', 'Series ID','Publication','Study Title']]

# 保存
df3.to_csv('Paper_and_Gsm.csv', sep=',', index=False)