In [2]:
import pandas as pd
import numpy as np
import os
import json

# 读取当前目录下的sample.tsv 
df = pd.read_csv('sample.tsv', sep='\t')
df['Time'] = df['Time'].fillna('')
df['Condition'] = df['Strain'] + '_' + df['Carbon Sources'] + '_' + df['Temperature'].fillna('NA') + '_' + df['Time'].fillna('NA')
df.head()

,Sample ID,Sample Name,Experiment,Run,Series Accession,Study Title,Species,Model,Library Seletion,Library Source,Library Strategy,Samples,Strain,Carbon Sources,Temperature,Time,Year,Condition
0,mt001001,GSM675519,SRX043463,SRR101401,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Barley_34C_rep1,wt,Barley,34°,,2011 Oct,wt_Barley_34°_
1,mt001002,"GSM675520,GSM675523","SRX043464, SRX043467","SRR101402,SRR101405",GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,"Barley_45C_rep1,Barley_45C_rep2",wt,Barley,45°,,2011 Oct,wt_Barley_45°_
2,mt001003,"GSM675524,GSM675525","SRX043468, SRX043469","SRR101406,SRR101407",GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,"Glucose_34C_rep1,Glucose_45C_rep2",wt,Glucose,34°,,2011 Oct,wt_Glucose_34°_
3,mt001004,GSM675521,SRX043465,SRR101403,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Glucose_45C_rep1,wt,Glucose,45°,,2011 Oct,wt_Glucose_45°_
4,mt001005,GSM675522,SRX043466,SRR101404,GSE27323,Transcriptomic response to substrate and tempe...,Myceliphothora thermophila,Illumina Genome Analyzer II,cDNA,transcriptomic,RNA-Seq,Alfalfa_45C_rep1,wt,Alfalfa,45°,,2011 Oct,wt_Alfalfa_45°_

In [3]:
# df保留Sample Number、Sample ID、Series ID、Study Title、Species、Strain、Sample Name、Canbon Sources、Temperature列
df_1 = df[['Sample ID', 'Series Accession','Study Title', 'Condition']]

# 如果Conditon最后一位是_，则去掉
df_1.loc[:,'Condition'] = df_1['Condition'].apply(lambda x: x[:-1] if x[-1] == '_' else x)

df_1

,Sample ID,Series Accession,Study Title,Condition
0,mt001001,GSE27323,Transcriptomic response to substrate and tempe...,wt_Barley_34°
1,mt001002,GSE27323,Transcriptomic response to substrate and tempe...,wt_Barley_45°
2,mt001003,GSE27323,Transcriptomic response to substrate and tempe...,wt_Glucose_34°
3,mt001004,GSE27323,Transcriptomic response to substrate and tempe...,wt_Glucose_45°
4,mt001005,GSE27323,Transcriptomic response to substrate and tempe...,wt_Alfalfa_45°
...,...,...,...,...
103,mt014008,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtLat-1_Arabinan_45°_4d
104,mt014009,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra_Aarabinose_45°_4h
105,mt014010,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra_Xylose_45°_4h
106,mt014011,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra_Arabinan_45°_4h
107,mt014012,GSE221464,The arabinose transporter MtLat-1 is involved ...,wt_Arabinan_45°_4h

In [4]:
# 读取dataset.tsv
df_2 = pd.read_csv('dataset.tsv', sep='\t')
df_2 = df_2[['Series Accession', 'PMID']]

df_2.head(20)

   Series Accession        PMID
0         GSE213575  37013645.0
1         GSE213573  37013645.0
2         GSE213570  37013645.0
3         GSE221464  36966330.0
4         GSE214002  36691040.0
5         GSE214142  36478865.0
6         GSE205182  36165620.0
7         GSE184074  35257374.0
8         GSE183387         NaN
9         GSE114057  31078793.0
10        GSE111986  30474279.0
11        GSE165516  33995328.0
12        GSE110062  29843921.0
13        GSE137286  31534479.0
14         GSE57235  24881579.0
15         GSE27323  21964414.0

In [5]:
# 将df_1和df_2合并，根据Series ID列
df_3 = pd.merge(df_1, df_2, on='Series Accession', how='left')

# 重置索引
df_3 = df_3.reset_index(drop=True)

df_3['PMID'] = df_3['PMID'].astype(str)
df_3 = df_3[df_3['PMID'] != 'nan']

# PMID去掉最后两个字符
df_3['PMID'] = df_3['PMID'].apply(lambda x: x[:-2] if x[-2:] == '.0' else x)

# 保存df_3为csv文件
df_3
# df_3.to_csv('sample_condition.csv', index=False)

,Sample ID,Series Accession,Study Title,Condition,PMID
0,mt001001,GSE27323,Transcriptomic response to substrate and tempe...,wt_Barley_34°,21964414
1,mt001002,GSE27323,Transcriptomic response to substrate and tempe...,wt_Barley_45°,21964414
2,mt001003,GSE27323,Transcriptomic response to substrate and tempe...,wt_Glucose_34°,21964414
3,mt001004,GSE27323,Transcriptomic response to substrate and tempe...,wt_Glucose_45°,21964414
4,mt001005,GSE27323,Transcriptomic response to substrate and tempe...,wt_Alfalfa_45°,21964414
...,...,...,...,...,...
103,mt014008,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtLat-1_Arabinan_45°_4d,36966330
104,mt014009,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra_Aarabinose_45°_4h,36966330
105,mt014010,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra_Xylose_45°_4h,36966330
106,mt014011,GSE221464,The arabinose transporter MtLat-1 is involved ...,MtAra_Arabinan_45°_4h,36966330
107,mt014012,GSE221464,The arabinose transporter MtLat-1 is involved ...,wt_Arabinan_45°_4h,36966330

In [8]:
def get_gene_exp(gene):
    """
    根据基因id，返回该基因在各个文献对应样本的TPM表达量
    """

    # 读取exp.tsv和sample_condition.csv，分别为基因的表达量(重复样本取平均值)和基因对应的文献与样本信息
    df_exp_fname = pd.read_csv('exp.tsv', sep='\t')
    df_condition = pd.read_csv('sample_condition.csv', sep=',')

    # 根据gene id从df_exp_fname中取出对应的行，并且将TPM标准化为log2(x + 1)
    df = df_exp_fname[df_exp_fname['Gene id'] == gene].copy()
    # df.iloc[:, 1:] = df.iloc[:, 1:].applymap(lambda x: np.log2(x + 1)).round(2)

    df_condition['Sample Exp'] = df_condition['Sample ID'].map(df.set_index('Gene id').iloc[:, 0:].T.to_dict()[gene])  # 原先是Sample Number，改叫为Sample ID

    # df_condition返回的是一个dataframe；构造字典
    output_dict = {
        'gene_id': {
            'gene_id': gene
        }
    }
    for _, row in df_condition.iterrows():
        pmid = str(row['PMID'])   # 原先是Publications，改叫为PMID
        if pmid not in output_dict['gene_id']:
            output_dict['gene_id'][pmid] = {
                'PMID': pmid,
                'Study Title': row['Study Title'],
            }
        sample_number = row['Sample ID']
        output_dict['gene_id'][pmid][sample_number] = {
            'Sample ID': sample_number,
            'Condition': row['Condition'],
            'Exp': str(row['Sample Exp'])
        }

    # # output_dict转为json格式
    # output_json = json.dumps(output_dict, indent=4)
    
    return output_dict

dict_gene_exp = get_gene_exp('MYCTH_2114025')
dict_gene_exp

{'gene_id': {'gene_id': 'MYCTH_2114025',
  '21964414': {'PMID': '21964414',
   'Study Title': 'Transcriptomic response to substrate and temperature in two thermophilic fungi, Myceliophthora thermophila and Thielavia terrestris, and a related mesophile, Chaetomium globosum',
   'mt001001': {'Sample ID': 'mt001001',
    'Condition': 'wt_Barley_34°',
    'Exp': '2.67'},
   'mt001002': {'Sample ID': 'mt001002',
    'Condition': 'wt_Barley_45°',
    'Exp': '3.55'},
   'mt001003': {'Sample ID': 'mt001003',
    'Condition': 'wt_Glucose_34°',
    'Exp': '2.35'},
   'mt001004': {'Sample ID': 'mt001004',
    'Condition': 'wt_Glucose_45°',
    'Exp': '2.29'},
   'mt001005': {'Sample ID': 'mt001005',
    'Condition': 'wt_Alfalfa_45°',
    'Exp': '4.34'}},
  '24881579': {'PMID': '24881579',
   'Study Title': 'Transcriptomic response to different biomass in Myceliophthora thermophila (Sporotrichum thermophile)',
   'mt002001': {'Sample ID': 'mt002001',
    'Condition': 'wt_Oat_45°',
    'Exp': '3.9'},
   'mt002002': {'Sample ID': 'mt002002',
    'Condition': 'wt_Triticale_45°',
    'Exp': '2.21'},
   'mt002003': {'Sample ID': 'mt002003',
    'Condition': 'wt_Canola_45°',
    'Exp': '4.13'},
   'mt002004': {'Sample ID': 'mt002004',
    'Condition': 'wt_Flax_45°',
    'Exp': '2.46'}},
  '29843921': {'PMID': '29843921',
   'Study Title': 'Transcriptional landscape of Myceliophthora thermophila responding to soluble starch and the role of regulator AmyR on polysaccharide degradation',
   'mt003001': {'Sample ID': 'mt003001',
    'Condition': 'wt_NoCarbon_45°_4h',
    'Exp': '8.16'},
   'mt003002': {'Sample ID': 'mt003002',
    'Condition': 'wt_Glucose_45°_4h',
    'Exp': '4.34'},
   'mt003003': {'Sample ID': 'mt003003',
    'Condition': 'wt_Starch_45°_4h',
    'Exp': '5.07'}},
  '31534479': {'PMID': '31534479',
   'Study Title': 'Myceliophthora thermophila Xyr1 is predominantly involved in xylan degradation and xylose catabolism',
   'mt004001': {'Sample ID': 'mt004001',
    'Condition': 'wt_Glucose_37°_2h',
    'Exp': '11.4'},
   'mt004002': {'Sample ID': 'mt004002',
    'Condition': 'wt_Xylose_37°_2h',
    'Exp': '14.01'},
   'mt004003': {'Sample ID': 'mt004003',
    'Condition': 'wt_Arabinose_37°_2h',
    'Exp': '15.06'},
   'mt004004': {'Sample ID': 'mt004004',
    'Condition': 'wt_Arabinoxylan_37°_2h',
    'Exp': '10.28'},
   'mt004005': {'Sample ID': 'mt004005',
    'Condition': 'wt_Arabinoxylan_37°_8h',
    'Exp': '9.38'},
   'mt004006': {'Sample ID': 'mt004006',
    'Condition': 'Xyr1 mutant_Glucose_37°_2h',
    'Exp': '12.75'},
   'mt004007': {'Sample ID': 'mt004007',
    'Condition': 'Xyr1 mutant_Xylose_37°_2h',
    'Exp': '14.73'},
   'mt004008': {'Sample ID': 'mt004008',
    'Condition': 'Xyr1 mutant_Arabinose_37°_2h',
    'Exp': '13.38'},
   'mt004009': {'Sample ID': 'mt004009',
    'Condition': 'Xyr1 mutant_Arabinoxylan_37°_2h',
    'Exp': '8.45'},
   'mt004010': {'Sample ID': 'mt004010',
    'Condition': 'Xyr1 mutant_Arabinoxylan_37°_8h',
    'Exp': '9.6'}},
  '30474279': {'PMID': '30474279',
   'Study Title': 'A novel conserved transcription factor CLR-4 regulates cellulase genes expression through controlling the intracellular cAMP level in ascomycete fungi',
   'mt005001': {'Sample ID': 'mt005001',
    'Condition': 'Mtclr_NoCarbon_45°_4h',
    'Exp': '1.37'},
   'mt005002': {'Sample ID': 'mt005002',
    'Condition': 'wt_NoCarbon_45°_4h',
    'Exp': '2.02'}},
  '31078793': {'PMID': '31078793',
   'Study Title': 'Engineering the Cellulolytic Fungus Myceliophthora thermophila into a Platform for Producing Commodity Chemicals Directly from Lignocellulose',
   'mt006001': {'Sample ID': 'mt006001',
    'Condition': 'wt_Avicel_45°',
    'Exp': '6.43'},
   'mt006002': {'Sample ID': 'mt006002',
    'Condition': 'JG141_Avicel_45°',
    'Exp': '11.84'},
   'mt006003': {'Sample ID': 'mt006003',
    'Condition': 'JG207_Avicel_45°',
    'Exp': '5.47'},
   'mt006004': {'Sample ID': 'mt006004',
    'Condition': 'JG207Ncclr2_Avicel_45°',
    'Exp': '6.44'},
   'mt006005': {'Sample ID': 'mt006005',
    'Condition': 'JG336_Avicel_45°',
    'Exp': '14.69'},
   'mt006006': {'Sample ID': 'mt006006',
    'Condition': 'wt_Glucose_45°',
    'Exp': '3.21'},
   'mt006007': {'Sample ID': 'mt006007',
    'Condition': 'JG207_Glucose_45°',
    'Exp': '7.09'}},
  '33995328': {'PMID': '33995328',
   'Study Title': 'Transcriptional profiling of Myceliophthora thermophila on galactose and metabolic engineering for improved galactose utilization',
   'mt007001': {'Sample ID': 'mt007001',
    'Condition': 'wt_NoCarbon_45°',
    'Exp': '4.92'},
   'mt007002': {'Sample ID': 'mt007002',
    'Condition': 'wt_Glucose_45°',
    'Exp': '3.14'},
   'mt007003': {'Sample ID': 'mt007003',
    'Condition': 'wt_Gal_45°',
    'Exp': '5.47'},
   'mt007004': {'Sample ID': 'mt007004',
    'Condition': 'wt_Gal_45°',
    'Exp': '13.39'},
   'mt007005': {'Sample ID': 'mt007005',
    'Condition': 'OEgal2_Gal_45°',
    'Exp': '3.96'},
   'mt007006': {'Sample ID': 'mt007006',
    'Condition': 'OEgal2_Gal_45°',
    'Exp': '27.9'}},
  '36478865': {'PMID': '36478865',
   'Study Title': 'PFK2/FBPase-2 is a potential target for metabolic engineering in the filamentous fungus Myceliophthora thermophila',
   'mt009001': {'Sample ID': 'mt009001',
    'Condition': 'wt_Glucose_45°_2d',
    'Exp': '6.82'},
   'mt009002': {'Sample ID': 'mt009002',
    'Condition': 'wt_Glucose_45°_4d',
    'Exp': '6.22'},
   'mt009003': {'Sample ID': 'mt009003',
    'Condition': 'Δpfk2_Glucose_45°_2d',
    'Exp': '5.93'},
   'mt009004': {'Sample ID': 'mt009004',
    'Condition': 'Δpfk2_Glucose_45°_4d',
    'Exp': '11.57'},
   'mt009005': {'Sample ID': 'mt009005',
    'Condition': 'Δpfk2_Glucose_45°_2d',
    'Exp': '6.06'},
   'mt009006': {'Sample ID': 'mt009006',
    'Condition': 'Δpfk2_Glucose_45°_2d',
    'Exp': '5.38'},
   'mt009007': {'Sample ID': 'mt009007',
    'Condition': 'Δpfk2_Glucose_45°_4d',
    'Exp': '9.76'},
   'mt009008': {'Sample ID': 'mt009008',
    'Condition': 'Δpfk2_Glucose_45°_2d',
    'Exp': '5.92'},
   'mt009009': {'Sample ID': 'mt009009',
    'Condition': 'Δpfk2_Glucose_45°_4d',
    'Exp': '7.52'}},
  '35257374': {'PMID': '35257374',
   'Study Title': 'Reconstruction and analysis genome-scale metabolic model of thermophilic fungus Myceliophthora thermophila',
   'mt010001': {'Sample ID': 'mt010001',
    'Condition': 'wt_Glucose_35°_66h',
    'Exp': '4.72'},
   'mt010002': {'Sample ID': 'mt010002',
    'Condition': 'wt_Glucose_40°_40h',
    'Exp': '7.0'},
   'mt010003': {'Sample ID': 'mt010003',
    'Condition': 'wt_Glucose_45°_40h',
    'Exp': '12.42'},
   'mt010004': {'Sample ID': 'mt010004',
    'Condition': 'wt_Glucose_50°_40h',
    'Exp': '5.38'}},
  '36165620': {'PMID': '36165620',
   'Study Title': 'MtTRC-1, a Novel Transcription Factor, Regulates Cellulase Production via Directly Modulating the Genes Expression of the Mthac-1 and Mtcbh-1 in Myceliophthora Thermophila',
   'mt011001': {'Sample ID': 'mt011001',
    'Condition': 'ΔMycth_90344_Avicel_45°_4h',
    'Exp': '3.82'},
   'mt011002': {'Sample ID': 'mt011002',
    'Condition': 'ΔMycth_90344_Avicel_45°_6h',
    'Exp': '3.91'},
   'mt011003': {'Sample ID': 'mt011003',
    'Condition': 'ΔMycth_90344_Starch_45°_4h',
    'Exp': '4.66'},
   'mt011004': {'Sample ID': 'mt011004',
    'Condition': 'wt_Avicel_45°_4h',
    'Exp': '4.27'},
   'mt011005': {'Sample ID': 'mt011005',
    'Condition': 'wt_Avicel_45°_6h',
    'Exp': '3.56'},
   'mt011006': {'Sample ID': 'mt011006',
    'Condition': 'wt_Starch_45°_4h',
    'Exp': '3.67'}},
  '37013645': {'PMID': '37013645',
   'Study Title': 'LaeA regulates mycelium growth by mediating H3K9 methylation in Myceliophthora thermophila [RNA-seq]',
   'mt012001': {'Sample ID': 'mt012001',
    'Condition': 'wt_Glucose_45°',
    'Exp': '5.03'},
   'mt012002': {'Sample ID': 'mt012002',
    'Condition': 'ΔlaeA_Glucose_45°',
    'Exp': '3.82'},
   'mt012003': {'Sample ID': 'mt012003',
    'Condition': 'Δgrf_Glucose_45°',
    'Exp': '4.28'},
   'mt012004': {'Sample ID': 'mt012004',
    'Condition': 'Δgrf_Glucose_45°',
    'Exp': '4.51'},
   'mt012005': {'Sample ID': 'mt012005',
    'Condition': 'Δgrf_Glucose_45°',
    'Exp': '3.78'},
   'mt012006': {'Sample ID': 'mt012006',
    'Condition': 'Δcre_Glucose_45°',
    'Exp': '4.72'},
   'mt012007': {'Sample ID': 'mt012007',
    'Condition': 'wt_Avicel_45°_2d',
    'Exp': '3.71'},
   'mt012008': {'Sample ID': 'mt012008',
    'Condition': 'ΔlaeA_Avicel_45°_2d',
    'Exp': '6.88'},
   'mt012009': {'Sample ID': 'mt012009',
    'Condition': 'wt_Avicel_45°_4d',
    'Exp': '6.17'},
   'mt012010': {'Sample ID': 'mt012010',
    'Condition': 'ΔlaeA_Avicel_45°_4d',
    'Exp': '5.92'},
   'mt012011': {'Sample ID': 'mt012011',
    'Condition': 'wt_Avicel_45°_6d',
    'Exp': '2.44'},
   'mt012012': {'Sample ID': 'mt012012',
    'Condition': 'ΔlaeA_Avicel_45°_6d',
    'Exp': '4.76'}},
  '36691040': {'PMID': '36691040',
   'Study Title': 'Weimberg pathway an alternative for utilization of D-xylose for Myceliophthora thermophila',
   'mt013001': {'Sample ID': 'mt013001',
    'Condition': 'JG207_Glucose_45°',
    'Exp': '10.67'},
   'mt013002': {'Sample ID': 'mt013002',
    'Condition': 'DF1102_Glucose_45°',
    'Exp': '14.64'},
   'mt013003': {'Sample ID': 'mt013003',
    'Condition': 'DF1406_Glucose_45°',
    'Exp': '12.47'},
   'mt013004': {'Sample ID': 'mt013004',
    'Condition': 'DF1501_Glucose_45°',
    'Exp': '20.0'}},
  '36966330': {'PMID': '36966330',
   'Study Title': 'The arabinose transporter MtLat-1 is involved in hemicellulase induction in Myceliophthora',
   'mt014001': {'Sample ID': 'mt014001',
    'Condition': 'wt_NoCarbon_45°_4h',
    'Exp': '4.92'},
   'mt014002': {'Sample ID': 'mt014002',
    'Condition': 'wt_Glucose_45°_4h',
    'Exp': '3.14'},
   'mt014003': {'Sample ID': 'mt014003',
    'Condition': 'wt_Xylose_45°_4h',
    'Exp': '4.36'},
   'mt014004': {'Sample ID': 'mt014004',
    'Condition': 'wt_Aarabinose_45°_4h',
    'Exp': '5.58'},
   'mt014005': {'Sample ID': 'mt014005',
    'Condition': 'wt_Arabinan_45°_2d',
    'Exp': '6.07'},
   'mt014006': {'Sample ID': 'mt014006',
    'Condition': 'wt_Arabinan_45°_4d',
    'Exp': '10.99'},
   'mt014007': {'Sample ID': 'mt014007',
    'Condition': 'MtLat-1_Arabinan_45°_2d',
    'Exp': '7.89'},
   'mt014008': {'Sample ID': 'mt014008',
    'Condition': 'MtLat-1_Arabinan_45°_4d',
    'Exp': '8.53'},
   'mt014009': {'Sample ID': 'mt014009',
    'Condition': 'MtAra_Aarabinose_45°_4h',
    'Exp': '6.06'},
   'mt014010': {'Sample ID': 'mt014010',
    'Condition': 'MtAra_Xylose_45°_4h',
    'Exp': '4.31'},
   'mt014011': {'Sample ID': 'mt014011',
    'Condition': 'MtAra_Arabinan_45°_4h',
    'Exp': '5.22'},
   'mt014012': {'Sample ID': 'mt014012',
    'Condition': 'wt_Arabinan_45°_4h',
    'Exp': '3.27'}}}}

In [21]:
#将output_dict 转为json文件
with open('gene_exp.json', 'w') as f:
    json.dump(dict_gene_exp, f, indent=4)