In [26]:
import pandas as pd
import numpy as np
import os
from collections import Counter
import json

In [27]:
# 读取数据
data = pd.read_excel('./Mt_Paper_filter.xlsx')
data.head()

,PMID,Title,Abstract,Keywords,Journal,Country,Year
0,25025273,Myceliophthora thermophila syn. Sporotrichum t...,Myceliophthora thermophila syn. Sporotrichum t...,"['Biomolecules', 'Myceliophthora thermophila, ...",Critical reviews in biotechnology,India,2016
1,32640074,Growth kinetics of Myceliophthora thermophila ...,AIMS: This work aimed to estimate the growth o...,"['N-acetylglucosamine', 'enzymes', 'growth kin...",Journal of applied microbiology,Brazil,2021 Jan
2,35450635,Extending the diversity of Myceliophthora ther...,Lytic polysaccharide monooxygenases (LPMOs) pl...,"['Active site segment', 'LPMOs', 'Lignocellulo...",Carbohydrate polymers,the Netherlands. Electronic address: peicheng....,2022 Jul 15
3,24995002,Genomic insights into the fungal lignocellulol...,The microbial conversion of solid cellulosic b...,"['CAZy', 'Myceliophthora thermophila', 'biofue...",Frontiers in microbiology,Sweden,2014
4,31534479,Myceliophthora thermophila Xyr1 is predominant...,BACKGROUND: Myceliophthora thermophila is a th...,"['Cellulose degradation', 'Myceliophthora ther...",Biotechnology for biofuels,The Netherlands. ISNI: 0000000120346234. GRID:...,2019

In [28]:
data_nc = pd.read_excel('./Nc_Paper_filter.xlsx')
data_nc.head()

,PMID,Title,Abstract,Keywords,Journal,Country,Year
0,35963473,Safety evaluation of Neurospora crassa mycopro...,Cultivation of filamentous fungi to produce su...,"['Food safety', 'Meat alternative', 'Mycoprote...",Food and chemical toxicology : an internationa...,USA. Electronic address: brad.bartholomai@bett...,2022 Oct
1,34265094,Revisiting the Neurospora crassa mitochondrial...,The mitochondrial genome of Neurospora crassa ...,"['DNA polymorphism', 'fungi', 'genomic rearran...",Letters in applied microbiology,Portugal,2021 Oct
2,31172300,Conidiation in Neurospora crassa: vegetative r...,"Asexual development, conidiation, in the filam...","['Asexual development', 'Conidiation', 'Neuros...",International microbiology : the official jour...,Germany. c.ruger-herreros@zmbh.uni-heidelberg.de,2020 Jan
3,32305463,Phosphorylation Timers in the Neurospora crass...,Circadian clocks are self-sustained oscillator...,"['Neurospora crassa', 'casein kinase 1', 'circ...",Journal of molecular biology,Germany,2020 May 29
4,25480699,Neurospora crassa: looking back and looking fo...,Investigation of the red bread mold that conta...,"['Fungal Genetics Stock Center', 'Neurospora c...",American journal of botany,California USA,2014 Dec

In [29]:
# 取data的Keywords这一列
keywords = data['Keywords']

# 将keywords的每一列的[]去掉
keywords = keywords.str.strip('[]')

# 去掉keywords中的单引号
keywords = keywords.str.replace("'", "")

# 将keywords整合到一个列表中
keywords_list = []
for i in keywords:
    keywords_list.extend(i.split(','))

# 将keywords_list中的空格去掉
keywords_list = [i.strip() for i in keywords_list]

# 将keywords_list每一个值的首字母改为大写
keywords_list = [i.capitalize() for i in keywords_list]

keywords_counts = Counter(keywords_list)

# 将keywords_counts转换为DataFrame
keywords_counts = pd.DataFrame.from_dict(keywords_counts, orient='index').reset_index()
keywords_counts.columns = ['keywords', 'counts']

# 将keywords_counts按照counts进行降序排列
keywords_counts = keywords_counts.sort_values(by='counts', ascending=False)
keywords_counts.to_csv('./Mt_keywords_counts.csv', index=False)


# json_data = keywords_counts.rename(columns={"counts": "value", "keywords": "name"}).to_dict("records")

# 遍历数据框中的每一行，将DataFrame转换为所需的json格式
json_data = []
for _, row in keywords_counts.iterrows():
    data = {"value": row["counts"], 
            "name": row["keywords"]}
    json_data.append(data)

# json_data = [
# {"value": row["counts"],
# "name": row["keywords"]}
# for _, row in keywords_counts.iterrows()
# ]

json_string = json.dumps(json_data, indent=4, ensure_ascii=False)

# 将json_string写入json文件
with open('./Mt_keywords_counts.json', 'w', encoding='utf-8') as f:
    f.write(json_string)

In [30]:
# 取data的Keywords这一列
keywords = data_nc['Keywords']

# 将keywords的每一列的[]去掉
keywords = keywords.str.strip('[]')

# 去掉keywords中的单引号
keywords = keywords.str.replace("'", "")

# 将keywords整合到一个列表中
keywords_list = []
for i in keywords:
    keywords_list.extend(i.split(','))

# 将keywords_list中的空格去掉
keywords_list = [i.strip() for i in keywords_list]

# 将keywords_list每一个值的首字母改为大写
keywords_list = [i.capitalize() for i in keywords_list]

keywords_counts = Counter(keywords_list)

# 将keywords_counts转换为DataFrame
keywords_counts = pd.DataFrame.from_dict(keywords_counts, orient='index').reset_index()
keywords_counts.columns = ['keywords', 'counts']

# 将keywords_counts按照counts进行降序排列
keywords_counts = keywords_counts.sort_values(by='counts', ascending=False)
keywords_counts.to_csv('./Nc_keywords_counts.csv', index=False)


# json_data = keywords_counts.rename(columns={"counts": "value", "keywords": "name"}).to_dict("records")

# 遍历数据框中的每一行，将DataFrame转换为所需的json格式
json_data = []
for _, row in keywords_counts.iterrows():
    data = {"value": row["counts"], 
            "name": row["keywords"]}
    json_data.append(data)

# json_data = [
# {"value": row["counts"],
# "name": row["keywords"]}
# for _, row in keywords_counts.iterrows()
# ]

json_string = json.dumps(json_data, indent=4, ensure_ascii=False)

# 将json_string写入json文件
with open('./Nc_keywords_counts.json', 'w', encoding='utf-8') as f:
    f.write(json_string)