In [2]:
import pandas as pd


# 读取mtd/search/myceliophthora_thermophila/data_processing_file/Gene_information_原始.tsv
df = pd.read_csv("Gene_information_原始.tsv", sep="\t")
df

,Gene,Chr,Start,End,Strand,Length,NCBI Gene ID,Protein_id,Uniport ID,Symbol,...,Type,Pathway Name,Pathway ID,Knum,EC_number,Description,PFAM,Cazy,Nucleic_acid_sequence,Amino_acid_sequence
0,MYCTH_100011,NC_016472.1,6881744.0,6884436.0,-,2693.0,11505753.0,XP_003660026,G2Q701,NaN,...,NaN,NaN,NaN,NaN,NaN,2OG-Fe(II) oxygenase superfamily,2OG-FeII_Oxy_2,NaN,ATGAGTAACATCACCAACAAAGTGATTTCCCAGACGCTGTCCCCCG...,MSNITNKVISQTLSPVDVPPKTFTSSDTTKSRLAAQRLRIATKRAA...
1,MYCTH_100068,NC_016473.1,5265193.0,5266157.0,-,965.0,11512455.0,XP_003662402,G2Q913,NaN,...,"CC,BP,MF,MF,MF,BP,BP,CC,MF",NaN,NaN,K01181,3.2.1.8,Belongs to the glycosyl hydrolase 11 (cellulas...,"CBM_1,Glyco_hydro_11",GH11: Glycoside Hydrolases (GHs) CBM1: Carbohy...,ATGGTTGCTCTCTCTTCTCTCCTCGTCGCTGCCTCTGCGGCGGCCG...,MVALSSLLVAASAAAVAVAAPSEALQKRQTLTSSQTGFHDGFYYSF...
2,MYCTH_100089,NC_016473.1,5175196.0,5176687.0,+,1492.0,11512426.0,XP_003662373,G2Q8Y3,NaN,...,"MF,MF,BP",NaN,NaN,NaN,NaN,"protocatechuate 3,4-dioxygenase activity",Dioxygenase_C,NaN,ATGACGCTCAAGCAGTTGCTCATGAGCGCGCTGCTCGCAGCACCCG...,MTLKQLLMSALLAAPALAHPAHKEKVYAHAALPLERKSLAHCAAKF...
3,MYCTH_100127,NC_016473.1,5035300.0,5035892.0,+,593.0,11512377.0,XP_003662324,G2Q8N0,NaN,...,NaN,NaN,NaN,K09780,NaN,YCII-related domain,YCII,NaN,ATGGCGACAGAAGCGCCCAAGAAGATGGAATGGCTCGTGGTCGTTC...,MATEAPKKMEWLVVVPDFPGAHEKRIAVRPQHFANLGPVKESGVFQ...
4,MYCTH_100290,NC_016473.1,4391122.0,4393687.0,+,2566.0,11512195.0,XP_003662142,G2Q7I4,NaN,...,"CC,BP",NaN,NaN,K11501,NaN,Mis6,CENP-I,NaN,ATGCCGTCCCCAGAGGATGATGACCTTGGCGGTCTCATCGGAGATC...,MPSPEDDDLGGLIGDLEAASKVPAKRRQTNIKSTVEKATALLYDRG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9287,MYCTH_t95,NC_016474.1,1785962.0,1786056.0,-,95.0,11507534.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9288,MYCTH_t96,NC_016474.1,1472358.0,1472429.0,-,72.0,11507441.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9289,MYCTH_t97,NC_016474.1,942762.0,942861.0,-,100.0,11512736.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9290,MYCTH_t98,NC_016474.1,86102.0,86183.0,-,82.0,11512532.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9291,MYCTH_t99,NC_016475.1,66526.0,66615.0,+,90.0,11509875.0,NaN,NaN,NaN,...,NaN,Aminoacyl-tRNA biosynthesis,mtm00970,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# df重排列，第一列为Gene，第二列为Symbol，第三列为Cazy，第四列为PFAM，第五列为Description
df_1 = df[["Gene", "Symbol", "Cazy", "PFAM", "Description", 
         "NCBI Gene ID",'Protein_id','KEGG','Knum', 'Uniport ID','EC_number','FungiDB','JGI',
         'Chr','Start','End','Strand','Length',
         'GO ID','ONTOLOGY','Type',
         'Pathway Name','Pathway ID']].copy()

df_1

,Gene,Symbol,Cazy,PFAM,Description,NCBI Gene ID,Protein_id,KEGG,Knum,Uniport ID,...,Chr,Start,End,Strand,Length,GO ID,ONTOLOGY,Type,Pathway Name,Pathway ID
0,MYCTH_100011,NaN,NaN,2OG-FeII_Oxy_2,2OG-Fe(II) oxygenase superfamily,11505753.0,XP_003660026,MYCTH_100011,NaN,G2Q701,...,NC_016472.1,6881744.0,6884436.0,-,2693.0,NaN,NaN,NaN,NaN,NaN
1,MYCTH_100068,NaN,GH11: Glycoside Hydrolases (GHs) CBM1: Carbohy...,"CBM_1,Glyco_hydro_11",Belongs to the glycosyl hydrolase 11 (cellulas...,11512455.0,XP_003662402,MYCTH_100068,K01181,G2Q913,...,NC_016473.1,5265193.0,5266157.0,-,965.0,"GO:0005576,GO:0005975,GO:0030248,GO:0004553,GO...","extracellular region,carbohydrate metabolic pr...","CC,BP,MF,MF,MF,BP,BP,CC,MF",NaN,NaN
2,MYCTH_100089,NaN,NaN,Dioxygenase_C,"protocatechuate 3,4-dioxygenase activity",11512426.0,XP_003662373,MYCTH_100089,NaN,G2Q8Y3,...,NC_016473.1,5175196.0,5176687.0,+,1492.0,"GO:0005506,GO:0016702,GO:0055114","iron ion binding,oxidoreductase activity, acti...","MF,MF,BP",NaN,NaN
3,MYCTH_100127,NaN,NaN,YCII,YCII-related domain,11512377.0,XP_003662324,MYCTH_100127,K09780,G2Q8N0,...,NC_016473.1,5035300.0,5035892.0,+,593.0,NaN,NaN,NaN,NaN,NaN
4,MYCTH_100290,NaN,NaN,CENP-I,Mis6,11512195.0,XP_003662142,MYCTH_100290,K11501,G2Q7I4,...,NC_016473.1,4391122.0,4393687.0,+,2566.0,"GO:0000776,GO:0034508","kinetochore,centromere complex assembly","CC,BP",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9287,MYCTH_t95,NaN,NaN,NaN,NaN,11507534.0,NaN,MYCTH_t95,NaN,NaN,...,NC_016474.1,1785962.0,1786056.0,-,95.0,NaN,NaN,NaN,Aminoacyl-tRNA biosynthesis,mtm00970
9288,MYCTH_t96,NaN,NaN,NaN,NaN,11507441.0,NaN,MYCTH_t96,NaN,NaN,...,NC_016474.1,1472358.0,1472429.0,-,72.0,NaN,NaN,NaN,Aminoacyl-tRNA biosynthesis,mtm00970
9289,MYCTH_t97,NaN,NaN,NaN,NaN,11512736.0,NaN,MYCTH_t97,NaN,NaN,...,NC_016474.1,942762.0,942861.0,-,100.0,NaN,NaN,NaN,Aminoacyl-tRNA biosynthesis,mtm00970
9290,MYCTH_t98,NaN,NaN,NaN,NaN,11512532.0,NaN,MYCTH_t98,NaN,NaN,...,NC_016474.1,86102.0,86183.0,-,82.0,NaN,NaN,NaN,Aminoacyl-tRNA biosynthesis,mtm00970
9291,MYCTH_t99,NaN,NaN,NaN,NaN,11509875.0,NaN,MYCTH_t99,NaN,NaN,...,NC_016475.1,66526.0,66615.0,+,90.0,NaN,NaN,NaN,Aminoacyl-tRNA biosynthesis,mtm00970

In [4]:
# 保存df_1到为tsv文件
df_1.to_csv("Gene_information.tsv", sep="\t", index=False)