In [14]:
import pandas as pd

mt_exp = pd.read_csv("Mt_TPM_Run221.csv") 
mt_sample = pd.read_csv("sample.tsv", sep="\t")

# mt_exp不保留第2到6列
mt_exp = mt_exp.drop(mt_exp.columns[1:6], axis=1)

# SRR 号码映射为 GSM 号码
id_map = dict(zip(mt_sample["Run"], mt_sample["Sample Name"])) 

# 替换 Mt_Exp 文件中的样本名称
new_columns = ["Gene id"] + [id_map[col] for col in mt_exp.columns[1:]] 
mt_exp.columns = new_columns

In [15]:
df = pd.DataFrame(mt_exp)
# df.to_csv("Mt_TPM_Run221_gsm.csv", index=False)

In [16]:
mt_exp = pd.read_csv("Mt_TPM_Run221_gsm.csv")
mt_sample = pd.read_csv("sample.tsv", sep="\t")

id_map = dict(zip(mt_sample["Sample Name"], mt_sample["Sample ID"])) 

new_columns = ["Gene id"] + [id_map[col] for col in mt_exp.columns[1:]] 
mt_exp.columns = new_columns

df_mtd_id = pd.DataFrame(mt_exp)

In [17]:
df_mtd_id

,Gene id,mt012002,mt012006,mt001001,mt009005,mt012003,mt014012,mt011005,mt013001,mt014009,...,mt014008,mt005001,mt008001,mt012002,mt006006,mt008016,mt002004,mt014003,mt012008,mt008006
0,MYCTH_2114025,3.635199,5.180080,2.672734,5.779671,4.915417,2.957272,3.581769,10.625067,6.249079,...,8.572209,1.400422,2.998193,4.001284,2.673436,24.688378,2.460176,4.878019,8.517545,8.857755
1,MYCTH_2293935,0.937768,0.139972,0.783317,1.987966,0.858355,0.135342,1.929814,1.527604,2.245146,...,8.286896,0.355707,0.000000,1.253005,1.476201,4.669780,1.735791,0.755498,3.090652,1.147893
2,MYCTH_2293936,0.821802,0.088590,1.652567,0.193570,0.296325,1.113572,3.925932,1.933676,2.643681,...,15.426090,0.540315,0.000000,1.321735,0.747444,0.000000,0.878881,1.721388,1.874604,1.743635
3,MYCTH_2051335,12.049987,6.123791,16.170740,25.240567,16.980881,6.401823,12.374617,12.296054,45.893773,...,41.329845,9.094783,53.920298,13.724517,11.826386,99.403401,19.527645,28.631662,22.645758,74.221704
4,MYCTH_2121898,0.000000,0.000000,0.000000,0.000000,0.004647,0.002015,0.000000,0.007580,0.000000,...,0.000000,0.004236,0.000000,0.000000,0.000000,0.000000,0.020672,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9287,MYCTH_103797,0.091119,0.176807,1.071907,0.289744,1.084238,0.844106,2.785896,0.542701,17.955671,...,9.424313,2.358900,2.867341,0.175860,0.512786,99.013388,4.823671,0.811166,14.050267,17.254641
9288,MYCTH_2071098,10.839302,4.671180,6.751942,21.749086,17.697005,9.269773,16.738754,11.499290,26.419564,...,17.488532,8.750767,26.304741,10.532928,16.043051,42.835784,16.741231,17.054809,19.822834,14.360359
9289,MYCTH_2114022,0.000000,0.000000,0.797269,0.000000,0.000000,0.025829,0.263061,0.097176,1.793566,...,0.000000,0.000000,0.447176,0.000000,0.000000,0.000000,0.795019,0.000000,0.196606,0.350502
9290,MYCTH_2114023,1.824369,0.488276,10.474582,0.533444,1.088822,0.354092,3.726592,0.444071,6.101600,...,2.361746,0.434294,4.597855,0.789199,0.643692,0.000000,1.513771,1.976594,1.516127,0.400428
9291,MYCTH_2313233,37.433992,12.964343,48.707584,26.261167,36.911835,16.820427,46.895326,26.585945,64.898993,...,43.535891,27.491544,136.930533,38.911364,27.393428,31.165653,53.345189,37.852793,37.668894,71.452121

In [18]:
import pandas as pd
import copy

df_mtd_id.columns = df_mtd_id.columns.str.replace('\.\d', '')

# copy.deepcopy()函数用于创建原始对象的完全独立副本（包括嵌套对象和所有内部对象），以便在进行更改时不会影响原始对象
df_mtd_id_new = copy.deepcopy(df_mtd_id.iloc[:,0:1])
columns = df_mtd_id.iloc[:,1:].columns

for col in columns:
    if len(pd.DataFrame(df_mtd_id[col]).columns)>=2: # series转DF
        df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
    else:
        df_mtd_id_new[col] = df_mtd_id[col]


df_mtd_id_new = df_mtd_id_new.round(2)
df_mtd_id_new

/tmp/ipykernel_23510/1247420412.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
/tmp/ipykernel_23510/1247420412.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col]
/tmp/ipykernel_23510/1247420412.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
/tmp/ipykernel_23510/1247420412.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
/tmp/ipykernel_23510/1247420412.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
/tmp/ipykernel_23510/1247420412.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
/tmp/ipykernel_23510/1247420412.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col].mean(axis=1)
/tmp/ipykernel_23510/1247420412.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col]
/tmp/ipykernel_23510/1247420412.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mtd_id_new[col] = df_mtd_id[col]

,Gene id,mt012002,mt012006,mt001001,mt009005,mt012003,mt014012,mt011005,mt013001,mt014009,...,mt012008,mt014011,mt002003,mt008016,mt012011,mt008017,mt007002,mt013002,mt001005,mt002004
0,MYCTH_2114025,3.82,4.72,2.67,6.06,4.28,3.27,3.56,10.67,6.06,...,6.88,5.22,4.13,19.88,2.44,17.43,3.14,14.64,4.34,2.46
1,MYCTH_2293935,1.10,0.28,0.78,1.79,1.50,0.25,2.54,1.76,1.78,...,3.71,1.51,0.35,6.28,4.88,6.55,2.51,4.79,1.27,1.74
2,MYCTH_2293936,1.07,0.83,1.65,0.53,1.02,0.98,3.44,2.15,1.61,...,1.47,0.95,2.65,0.30,13.46,1.68,7.08,1.95,0.80,0.88
3,MYCTH_2051335,12.89,6.80,16.17,29.16,16.34,9.93,13.58,12.14,41.87,...,22.97,17.42,14.69,85.47,46.05,82.12,12.97,9.45,12.16,19.53
4,MYCTH_2121898,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9287,MYCTH_103797,0.13,0.13,1.07,0.30,1.08,0.96,2.94,0.58,15.78,...,13.31,1.77,3.75,85.37,33.65,101.51,0.55,2.32,3.14,4.82
9288,MYCTH_2071098,10.69,4.83,6.75,22.38,17.00,9.86,16.28,10.57,22.87,...,18.52,11.26,10.26,37.60,26.14,30.14,11.23,11.49,10.96,16.74
9289,MYCTH_2114022,0.00,0.00,0.80,0.00,0.00,0.01,0.70,0.10,1.13,...,0.10,0.05,0.00,0.00,0.33,0.00,0.06,0.05,0.16,0.80
9290,MYCTH_2114023,1.31,0.30,10.47,0.66,0.88,0.49,3.63,0.62,6.40,...,1.66,0.53,7.01,0.83,1.87,0.83,0.51,0.54,6.65,1.51
9291,MYCTH_2313233,38.17,13.63,48.71,25.30,36.65,21.96,45.27,22.44,61.07,...,40.76,35.73,38.34,31.52,56.59,39.95,27.08,20.79,42.90,53.35

In [19]:
df_mtd_id_new.to_csv('exp.csv',index=False)